<?php

/**
 * Places near IXORA Homestay (Niduvaloor Gate / Irikkur · 12.043528, 75.466966).
 * Distances are approximate road km from the homestay pin (editable in Admin → Nearby places).
 *
 * Exact pin: https://maps.app.goo.gl/ht4uuSDodgYPxeKT6
 * (resolves to 12.043528, 75.466966 — use coords for directions/embed, not a text search).
 */
return [
    'homestay' => [
        'lat' => 12.043528,
        'lng' => 75.466966,
        'label' => 'IXORA Homestay, Niduvaloor Gate, Irikkur',
        /** Exact share pin from Google Maps */
        'maps_link' => 'https://maps.app.goo.gl/ht4uuSDodgYPxeKT6',
        /**
         * Directions origin must be lat,lng (text search jumps to a different POI).
         * Label is only for the embed marker text.
         */
        'maps_query' => '12.043528,75.466966',
        'embed' => 'https://www.google.com/maps?q=12.043528,75.466966+(IXORA+Homestay)&z=16&output=embed',
    ],

    /**
     * Unified tourist attractions (nature + heritage + sacred).
     * title = short card heading; type = badge label; cat = filter tokens.
     * Road km / drive mins measured from Niduvaloor Gate toward each place.
     */
    'attractions' => [
        [
            'title' => 'Mamanikkunnu Temple',
            'type' => 'Temple',
            'cat' => 'temple',
            'blurb' => 'Devi temple at Irikkur — a favourite local pilgrimage stop near the homestay.',
            'direction' => 'Southwest / west',
            'distance_km' => 6,
            'drive_mins' => 12,
            'maps_query' => 'Mamanikkunnu Sri Mahadevi Temple Irikkur',
            'image' => 'assets/images/sacred-mamanikkunnu.jpg',
            'alt' => 'Mamanikkunnu Sri Mahadevi Temple near Irikkur Kannur',
        ],
        [
            'title' => 'Nilamuttam Maqam',
            'type' => 'Pilgrimage',
            'cat' => 'heritage temple',
            'blurb' => 'Historic maqam and masjid at Irikkur — an important Muslim worship centre.',
            'direction' => 'Southwest / west',
            'distance_km' => 7,
            'drive_mins' => 15,
            'maps_query' => 'Nilamuttam Maqam Masjid Irikkur',
            'image' => 'assets/images/sacred-nilamuttam.jpg',
            'alt' => 'Nilamuttam Maqam and Masjid at Irikkur Kannur',
        ],
        [
            'title' => 'Puralimala Madappura',
            'type' => 'Temple / culture',
            'cat' => 'temple heritage',
            'blurb' => 'Muthappan worship centre in the Puralimala hills, known for Theyyam tradition.',
            'direction' => 'East / northeast',
            'distance_km' => 20,
            'drive_mins' => 35,
            'maps_query' => 'Sree Puralimala Muthapan Madappura Kannur',
            'image' => 'assets/images/sacred-puralimala.jpg',
            'alt' => 'Sree Puralimala Muthapan Madappura sacred grove Kannur',
        ],
        [
            'title' => 'Mridanga Shaileswari',
            'type' => 'Temple',
            'cat' => 'temple heritage',
            'blurb' => 'Muzhakkunnu Bhagavathi temple linked with Veera Pazhassi Raja and local tradition.',
            'direction' => 'East / southeast',
            'distance_km' => 25,
            'drive_mins' => 40,
            'maps_query' => 'Muzhakkunnu Sree Mridanga Shaileswari Devi Temple',
            'image' => 'assets/images/sacred-muzhakkunnu.jpg',
            'alt' => 'Muzhakkunnu Sree Mridanga Shaileswari Devi Temple',
        ],
        [
            'title' => 'Rajarajeswara Temple',
            'type' => 'Temple',
            'cat' => 'temple heritage',
            'blurb' => 'A major historic Shiva temple at Taliparamba.',
            'direction' => 'North',
            'distance_km' => 28,
            'drive_mins' => 45,
            'maps_query' => 'Sri Rajarajeswara Temple Taliparamba',
            'image' => 'assets/images/explore-rajarajeswara-temple-taliparamba.jpg',
            'alt' => 'Sree Rajarajeswara Temple Taliparamba Kerala traditional entrance gateway',
        ],
        [
            'title' => 'Palakkayam Thattu',
            'type' => 'Hill station',
            'cat' => 'hill adventure',
            'blurb' => 'Mist, panoramic views, sunset, trekking and adventure.',
            'direction' => 'East',
            'distance_km' => 30,
            'drive_mins' => 50,
            'maps_query' => 'Palakkayam Thattu Kannur',
            'image' => 'assets/images/explore-palakkayam-thattu-hill-station-kannur.jpg',
            'alt' => 'Palakkayam Thattu misty Western Ghats hill station viewpoint near Kannur Kerala',
        ],
        [
            'title' => 'Kunnathoor Padi',
            'type' => 'Temple / culture',
            'cat' => 'temple heritage',
            'blurb' => 'Hill-forest Muthappan worship site — a classic North Malabar sacred landscape.',
            'direction' => 'North',
            'distance_km' => 30,
            'drive_mins' => 50,
            'maps_query' => 'Kunnathoor Padi Muthappan Temple Kannur',
            'image' => 'assets/images/sacred-kunnathoor.jpg',
            'alt' => 'Kunnathoor Padi Muthappan worship site Kannur',
        ],
        [
            'title' => 'Peralassery Temple Pond',
            'type' => 'Temple',
            'cat' => 'temple',
            'blurb' => 'Subrahmanya temple celebrated for its serene, photogenic temple pond.',
            'direction' => 'Southwest',
            'distance_km' => 32,
            'drive_mins' => 50,
            'maps_query' => 'Sree Peralassery Temple Pond Kannur',
            'image' => 'assets/images/sacred-peralassery.jpg',
            'alt' => 'Sree Peralassery Temple and temple pond Kannur',
        ],
        [
            'title' => 'Paithalmala',
            'type' => 'Hill station',
            'cat' => 'hill adventure',
            'blurb' => 'Western Ghats trekking, forest trails and mountain views.',
            'direction' => 'East',
            'distance_km' => 38,
            'drive_mins' => 60,
            'maps_query' => 'Paithalmala Tourism Kannur',
            'image' => 'assets/images/explore-paithalmala-western-ghats-kannur.jpg',
            'alt' => 'Paithalmala Western Ghats misty mountain ridges near Kannur Kerala',
        ],
        [
            'title' => 'Kottiyoor Temple',
            'type' => 'Temple',
            'cat' => 'temple',
            'blurb' => 'Famed Shiva shrine and the annual Vaishakha Mahotsavam pilgrimage.',
            'direction' => 'East / southeast',
            'distance_km' => 40,
            'drive_mins' => 60,
            'maps_query' => 'Kottiyoor Temple Kannur',
            'image' => 'assets/images/sacred-kottiyoor.jpg',
            'alt' => 'Kottiyoor Temple forest shrine Kannur',
        ],
        [
            'title' => 'Ezharakund Waterfalls',
            'type' => 'Waterfall',
            'cat' => 'waterfall',
            'blurb' => 'Seven-tier falls, natural pools and a nature trail near Paithalmala.',
            'direction' => 'East',
            'distance_km' => 40,
            'drive_mins' => 65,
            'maps_query' => 'Ezharakund Waterfalls Paithalmala',
            'image' => 'assets/images/explore-ezharakund-waterfalls-paithalmala.jpg',
            'alt' => 'Ezharakund Waterfalls near Paithalmala Kannur',
        ],
        [
            'title' => 'Parassinikadavu Temple',
            'type' => 'Temple / culture',
            'cat' => 'temple',
            'blurb' => 'Kannur’s celebrated Muthappan temple on the Valapattanam River.',
            'direction' => 'North',
            'distance_km' => 40,
            'drive_mins' => 60,
            'maps_query' => 'Parassinikadavu Muthappan Temple',
            'image' => 'assets/images/explore-parassinikadavu-muthappan-temple.jpg',
            'alt' => 'Parassinikadavu Muthappan Temple on Valapattanam River Kannur Kerala',
        ],
        [
            'title' => 'Alakapuri Waterfalls',
            'type' => 'Waterfall',
            'cat' => 'waterfall',
            'blurb' => 'Kanjirakolly scenery, a forest waterfall and cool pools.',
            'direction' => 'East / southeast',
            'distance_km' => 42,
            'drive_mins' => 65,
            'maps_query' => 'Alakapuri Waterfalls Kannur',
            'image' => 'assets/images/explore-alakapuri-waterfalls-kannur.jpg',
            'alt' => 'Alakapuri Waterfalls Kannur',
        ],
        [
            'title' => 'Vismaya Water Park',
            'type' => 'Family attraction',
            'cat' => 'family',
            'blurb' => 'A water and amusement park for a full family day out.',
            'direction' => 'Northwest',
            'distance_km' => 45,
            'drive_mins' => 70,
            'maps_query' => 'Vismaya Amusement Park Kannur',
            'image' => 'assets/images/explore-vismaya-amusement-park-kannur.jpg',
            'alt' => 'Vismaya Water Theme Park entrance Kannur Kerala',
        ],
        [
            'title' => 'St. Angelo Fort',
            'type' => 'Historic attraction',
            'cat' => 'heritage',
            'blurb' => 'A seaside fort and one of Kannur’s best-known heritage sites.',
            'direction' => 'Northwest',
            'distance_km' => 48,
            'drive_mins' => 75,
            'maps_query' => 'St Angelo Fort Kannur',
            'image' => 'assets/images/explore-st-angelo-fort-kannur.jpg',
            'alt' => 'St Angelo Fort Kannur seaside Portuguese fort with cannons and Arabian Sea',
        ],
        [
            'title' => 'Cherukunnu Temple',
            'type' => 'Temple',
            'cat' => 'temple',
            'blurb' => 'Famous Annapoorneshwari temple at Cherukunnu.',
            'direction' => 'Northwest',
            'distance_km' => 48,
            'drive_mins' => 75,
            'maps_query' => 'Cherukunnu Sree Annapoorneswary Temple',
            'image' => 'assets/images/sacred-cherukunnu.jpg',
            'alt' => 'Cherukunnu Sree Annapoorneswary Temple',
        ],
        [
            'title' => 'Muzhappilangad Beach',
            'type' => 'Beach',
            'cat' => 'beach',
            'blurb' => 'Kerala’s famous drive-in beach, with a long shore for sunset drives.',
            'direction' => 'Northwest',
            'distance_km' => 50,
            'drive_mins' => 80,
            'maps_query' => 'Muzhappilangad Drive In Beach',
            'image' => 'assets/images/explore-muzhappilangad-drive-in-beach.jpg',
            'alt' => 'Muzhappilangad Drive-in Beach empty shoreline Kannur Kerala at sunset',
        ],
        [
            'title' => 'Madayi Para',
            'type' => 'Nature / heritage',
            'cat' => 'heritage nature',
            'blurb' => 'Laterite landscape, seasonal greenery and a heritage viewpoint.',
            'direction' => 'North / northwest',
            'distance_km' => 50,
            'drive_mins' => 75,
            'maps_query' => 'Madayi Para Kannur',
            'image' => 'assets/images/explore-madayi-para-kannur.jpg',
            'alt' => 'Madayi Para laterite hills Kannur',
        ],
        [
            'title' => 'Madayi Kavu',
            'type' => 'Temple',
            'cat' => 'temple',
            'blurb' => 'Major Bhagavathi temple at Madayi — a key North Malabar sacred site.',
            'direction' => 'North / northwest',
            'distance_km' => 50,
            'drive_mins' => 75,
            'maps_query' => 'Madayi Kavu Sri Thiruvarkkaattu Kaavu Bhagavati Temple',
            'image' => 'assets/images/sacred-madayi-kavu.jpg',
            'alt' => 'Madayi Kavu Bhagavati Temple Kannur',
        ],
    ],

    /** @deprecated Use attractions; kept for older helpers. */
    'sacred' => [],
];
