<?php

/**
 * Named image slots used across frontend templates.
 * Upload in Media Library, then assign here via Admin → Site Images.
 * Until assigned, each slot uses its fallback under public/assets/images.
 */
return [
    'slots' => [
        // Home
        'home.hero' => [
            'label' => 'Home — Hero',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-niduvaloor-exterior-sunset.jpg',
            'alt' => 'IXORA Homestay Niduvaloor exterior at sunset with play area Kannur Kerala',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.stack_tall' => [
            'label' => 'Home — Photo stack tall',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-front-stairs-evening.jpg',
            'alt' => 'IXORA Homestay front stairs and balcony at dusk Niduvaloor Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.stack_1' => [
            'label' => 'Home — Photo stack 1',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-living-room-lounge.jpg',
            'alt' => 'Modern living lounge with blue sofas at IXORA Homestay Niduvaloor',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.stack_2' => [
            'label' => 'Home — Photo stack 2',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-bedroom-double-green.jpg',
            'alt' => 'Bright double bedroom with green accents at IXORA Homestay Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.feature_stay' => [
            'label' => 'Home — Stay feature',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-bedroom-wood-ceiling.jpg',
            'alt' => 'Modern bedroom with wood ceiling at IXORA 2 BHK Homestay Niduvaloor Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.feature_events' => [
            'label' => 'Home — Events feature',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-outdoor-screen-courtyard.jpg',
            'alt' => 'Outdoor courtyard with screen stage for events at IXORA Homestay Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.reel_1' => [
            'label' => 'Home — Reel evening lights',
            'group' => 'home_reels',
            'fallback' => 'assets/images/ixora-homestay-evening-lights-cottage.jpg',
            'alt' => 'IXORA 2 BHK cottage warmly lit at blue hour Niduvaloor Gate',
            'caption' => 'Evening Lights',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.reel_2' => [
            'label' => 'Home — Reel garden swing',
            'group' => 'home_reels',
            'fallback' => 'assets/images/ixora-homestay-marigold-garden-swing.jpg',
            'alt' => 'Marigold-decorated garden swing at IXORA Homestay Kannur',
            'caption' => 'Garden Swing',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.reel_3' => [
            'label' => 'Home — Reel living lounge',
            'group' => 'home_reels',
            'fallback' => 'assets/images/ixora-homestay-living-room-lounge.jpg',
            'alt' => 'Modern living lounge at IXORA Homestay Niduvaloor Kannur',
            'caption' => 'Living Lounge',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.reel_4' => [
            'label' => 'Home — Reel giraffe bench',
            'group' => 'home_reels',
            'fallback' => 'assets/images/ixora-homestay-giraffe-bench-night.jpg',
            'alt' => 'Yellow giraffe garden bench photo spot at IXORA Homestay',
            'caption' => 'Photo Spot',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.reel_5' => [
            'label' => 'Home — Reel forest cottage',
            'group' => 'home_reels',
            'fallback' => 'assets/images/ixora-homestay-exterior-aerial.jpg',
            'alt' => 'IXORA Homestay cottage amid forest greenery Niduvaloor Kannur',
            'caption' => 'Forest Cottage',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.place_1' => [
            'label' => 'Home — Nearby Palakkayam',
            'group' => 'home_places',
            'fallback' => 'assets/images/explore-palakkayam-thattu-hill-station-kannur.jpg',
            'alt' => 'Palakkayam Thattu hill station near IXORA Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'home.place_2' => [
            'label' => 'Home — Nearby Ezharakund',
            'group' => 'home_places',
            'fallback' => 'assets/images/explore-ezharakund-waterfalls-paithalmala.jpg',
            'alt' => 'Ezharakund waterfalls near Paithalmala Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'home.place_3' => [
            'label' => 'Home — Nearby St Angelo',
            'group' => 'home_places',
            'fallback' => 'assets/images/explore-st-angelo-fort-kannur.jpg',
            'alt' => 'St. Angelo Fort seaside heritage site in Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'home.place_4' => [
            'label' => 'Home — Nearby Muzhappilangad',
            'group' => 'home_places',
            'fallback' => 'assets/images/explore-muzhappilangad-drive-in-beach.jpg',
            'alt' => 'Muzhappilangad drive-in beach near IXORA Kerala',
            'width' => 800,
            'height' => 533,
        ],
        'home.gallery_1' => [
            'label' => 'Home gallery — Exterior dusk',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-twilight-front-view.jpg',
            'alt' => 'Twilight front view of IXORA Homestay Niduvaloor Kannur',
            'caption' => 'Twilight cottage',
            'category' => 'homestay',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_2' => [
            'label' => 'Home gallery — Bedroom',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-bedroom-double-green.jpg',
            'alt' => 'Bright double bedroom at IXORA 2 BHK Homestay Kannur',
            'caption' => 'Bedroom',
            'category' => 'bedrooms',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_3' => [
            'label' => 'Home gallery — Dining',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-dining-room-marble.jpg',
            'alt' => 'Marble dining table at IXORA Homestay Niduvaloor Kannur',
            'caption' => 'Dining room',
            'category' => 'living',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_4' => [
            'label' => 'Home gallery — Event courtyard',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-outdoor-screen-courtyard.jpg',
            'alt' => 'Outdoor screen courtyard for events at IXORA Homestay',
            'caption' => 'Event courtyard',
            'category' => 'events',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_5' => [
            'label' => 'Home gallery — Living lounge',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-living-room-lounge.jpg',
            'alt' => 'Living lounge at IXORA Homestay Niduvaloor',
            'caption' => 'Living lounge',
            'category' => 'living',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_6' => [
            'label' => 'Home gallery — Garden walkway',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-garden-walkway-forest.jpg',
            'alt' => 'Garden walkway beside forest at IXORA Homestay Kannur',
            'caption' => 'Garden walkway',
            'category' => 'courtyard',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_7' => [
            'label' => 'Home gallery — Kitchenette',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-guest-kitchen.jpg',
            'alt' => 'Guest kitchenette at IXORA Homestay Kannur',
            'caption' => 'Kitchenette',
            'category' => 'living',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.gallery_8' => [
            'label' => 'Home gallery — Photo point',
            'group' => 'home_gallery',
            'fallback' => 'assets/images/ixora-homestay-marigold-garden-swing.jpg',
            'alt' => 'Flower-decked garden swing photo point at IXORA Homestay',
            'caption' => 'Photo point',
            'category' => 'photo',
            'width' => 1600,
            'height' => 1067,
        ],
        'home.faq_aside' => [
            'label' => 'Home — FAQ aside',
            'group' => 'home',
            'fallback' => 'assets/images/ixora-homestay-evening-lights-cottage.jpg',
            'alt' => 'IXORA Homestay cottage exterior at dusk Niduvaloor',
            'width' => 1600,
            'height' => 1067,
        ],

        // Shared aside
        'shared.evening_aside' => [
            'label' => 'Shared — Evening aside (booking/contact/FAQ)',
            'group' => 'shared',
            'fallback' => 'assets/images/ixora-homestay-night-sign-crescent.jpg',
            'alt' => 'IXORA Homestay night exterior with welcome sign, Niduvaloor Gate Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'contact.visit' => [
            'label' => 'Contact — Visit media',
            'group' => 'contact',
            'fallback' => 'assets/images/ixora-homestay-welcome-sign-garden.jpg',
            'alt' => 'IXORA Home Stay Niduvaloor welcome sign and entrance garden',
            'width' => 1600,
            'height' => 1067,
        ],

        // Stay
        'stay.room_1' => [
            'label' => 'Stay — Bedroom 1',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-bedroom-double-green.jpg',
            'alt' => 'Bedroom 1 at IXORA 2 BHK Homestay Niduvaloor Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'stay.room_2' => [
            'label' => 'Stay — Bedroom 2',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-bedroom-wood-ceiling.jpg',
            'alt' => 'Bedroom 2 with wood ceiling at IXORA Homestay Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'stay.living' => [
            'label' => 'Stay — Living room',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-living-room-lounge.jpg',
            'alt' => 'Living room lounge at IXORA Homestay Niduvaloor Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'stay.kitchen' => [
            'label' => 'Stay — Kitchen',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-guest-kitchen.jpg',
            'alt' => 'Guest kitchenette with fridge at IXORA Homestay Niduvaloor Kerala',
            'width' => 1600,
            'height' => 1067,
        ],
        'stay.courtyard' => [
            'label' => 'Stay — Courtyard',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-garden-walkway-forest.jpg',
            'alt' => 'Private garden courtyard walkway at IXORA Homestay Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'stay.photo_point' => [
            'label' => 'Stay — Photo point',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-giraffe-bench-night.jpg',
            'alt' => 'Giraffe photo bench at IXORA Homestay Niduvaloor Gate',
            'width' => 1600,
            'height' => 1067,
        ],
        'stay.wide' => [
            'label' => 'Stay — Wide media / tour poster',
            'group' => 'stay',
            'fallback' => 'assets/images/ixora-homestay-tour-poster.jpg',
            'alt' => 'Property tour of IXORA 2 BHK Homestay at Niduvaloor Gate Kannur',
            'width' => 1280,
            'height' => 720,
        ],

        // Events
        'events.hero' => [
            'label' => 'Events — Hero',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-outdoor-screen-courtyard.jpg',
            'alt' => 'Outdoor event courtyard and screen at IXORA Homestay Niduvaloor Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'events.card_1' => [
            'label' => 'Events — Birthday',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-outdoor-screen-courtyard.jpg',
            'alt' => 'Celebration courtyard setup at IXORA event venue Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'events.card_2' => [
            'label' => 'Events — Engagement',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-marigold-garden-swing.jpg',
            'alt' => 'Decorated garden swing for engagement photos at IXORA Homestay',
            'width' => 1600,
            'height' => 1067,
        ],
        'events.card_3' => [
            'label' => 'Events — Family dining',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-dining-room-marble.jpg',
            'alt' => 'Family dining area at IXORA Homestay Niduvaloor',
            'width' => 1600,
            'height' => 1067,
        ],
        'events.card_4' => [
            'label' => 'Events — Dancing',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-reception-entrance-night.jpg',
            'alt' => 'Evening venue entrance for gatherings at IXORA Homestay',
            'width' => 1600,
            'height' => 1067,
        ],
        'events.card_5' => [
            'label' => 'Events — Campfire',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-garden-walkway-forest.jpg',
            'alt' => 'Courtyard evening space at IXORA Homestay Kannur',
            'width' => 1600,
            'height' => 1067,
        ],
        'events.card_6' => [
            'label' => 'Events — Photo point',
            'group' => 'events',
            'fallback' => 'assets/images/ixora-homestay-giraffe-bench-night.jpg',
            'alt' => 'Giraffe photo bench at IXORA celebration venue',
            'width' => 1600,
            'height' => 1067,
        ],

        // Explore
        'explore.hero' => [
            'label' => 'Explore — Hero',
            'group' => 'explore',
            'fallback' => 'assets/images/explore-kannur-travel-hero-banner.jpg',
            'alt' => 'Kannur Kerala coastline fort and hills travel banner near IXORA Homestay Niduvaloor',
            'width' => 1280,
            'height' => 720,
        ],
        'explore.place_1' => [
            'label' => 'Explore — Palakkayam Thattu',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-palakkayam-thattu-hill-station-kannur.jpg',
            'alt' => 'Palakkayam Thattu hill station mist and panoramic views Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_2' => [
            'label' => 'Explore — Paithalmala',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-paithalmala-western-ghats-kannur.jpg',
            'alt' => 'Paithalmala Western Ghats trekking viewpoint Kannur Kerala',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_3' => [
            'label' => 'Explore — Ezharakund',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-ezharakund-waterfalls-paithalmala.jpg',
            'alt' => 'Ezharakund seven-tier waterfalls near Paithalmala Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_4' => [
            'label' => 'Explore — Alakapuri',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-alakapuri-waterfalls-kannur.jpg',
            'alt' => 'Alakapuri waterfalls Kanjirakolly forest Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_5' => [
            'label' => 'Explore — Muthappan Temple',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-parassinikadavu-muthappan-temple.jpg',
            'alt' => 'Parassinikadavu Muthappan Temple Theyyam tradition Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_6' => [
            'label' => 'Explore — Vismaya',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-vismaya-amusement-park-kannur.jpg',
            'alt' => 'Vismaya amusement and water park Kannur Kerala',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_7' => [
            'label' => 'Explore — Rajarajeswara',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-rajarajeswara-temple-taliparamba.jpg',
            'alt' => 'Sri Rajarajeswara Temple historic site Taliparamba Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_8' => [
            'label' => 'Explore — Madayi Para',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-madayi-para-kannur.jpg',
            'alt' => 'Madayi Para laterite landscape and heritage viewpoint Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_9' => [
            'label' => 'Explore — St Angelo Fort',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-st-angelo-fort-kannur.jpg',
            'alt' => 'St Angelo Fort seaside heritage fort Kannur Kerala',
            'width' => 800,
            'height' => 533,
        ],
        'explore.place_10' => [
            'label' => 'Explore — Muzhappilangad',
            'group' => 'explore_places',
            'fallback' => 'assets/images/explore-muzhappilangad-drive-in-beach.jpg',
            'alt' => 'Muzhappilangad drive-in beach Kannur Kerala',
            'width' => 800,
            'height' => 533,
        ],
        'explore.trip_1' => [
            'label' => 'Explore — Trip Palakkayam',
            'group' => 'explore_trips',
            'fallback' => 'assets/images/explore-palakkayam-thattu-hill-station-kannur.jpg',
            'alt' => 'Day trip to Palakkayam Thattu from IXORA Niduvaloor',
            'width' => 800,
            'height' => 533,
        ],
        'explore.trip_2' => [
            'label' => 'Explore — Trip Ezharakund',
            'group' => 'explore_trips',
            'fallback' => 'assets/images/explore-ezharakund-waterfalls-paithalmala.jpg',
            'alt' => 'Ezharakund seven-tier waterfalls near Paithalmala Kannur',
            'width' => 800,
            'height' => 533,
        ],
        'explore.trip_3' => [
            'label' => 'Explore — Trip Beach',
            'group' => 'explore_trips',
            'fallback' => 'assets/images/explore-muzhappilangad-drive-in-beach.jpg',
            'alt' => 'Kannur coast trip to Muzhappilangad drive-in beach',
            'width' => 800,
            'height' => 533,
        ],

        // Gallery page
        'gallery.01' => ['label' => 'Gallery 01', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-niduvaloor-exterior-sunset.jpg', 'alt' => 'IXORA Homestay Niduvaloor exterior at sunset with play area Kannur', 'caption' => 'Homestay at dusk', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.02' => ['label' => 'Gallery 02', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-courtyard-sunset-sign.jpg', 'alt' => 'IXORA Homestay courtyard at golden hour with welcome sign Niduvaloor', 'caption' => 'Courtyard sunset', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.03' => ['label' => 'Gallery 03', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-entrance-golden-hour.jpg', 'alt' => 'IXORA Homestay entrance and playground at golden hour Kannur', 'caption' => 'Golden hour entrance', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.04' => ['label' => 'Gallery 04', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-forest-edge-dusk.jpg', 'alt' => 'IXORA Homestay cottage at forest edge with evening lights Kerala', 'caption' => 'Forest edge dusk', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.05' => ['label' => 'Gallery 05', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-front-stairs-evening.jpg', 'alt' => 'IXORA Homestay front stairs and balcony at dusk Niduvaloor Kannur', 'caption' => 'Front stairs evening', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.06' => ['label' => 'Gallery 06', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-evening-lights-cottage.jpg', 'alt' => 'IXORA 2 BHK cottage warmly lit at blue hour Niduvaloor Gate', 'caption' => 'Evening cottage lights', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.07' => ['label' => 'Gallery 07', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-twilight-front-view.jpg', 'alt' => 'Twilight front view of IXORA Homestay surrounded by trees', 'caption' => 'Twilight front view', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.08' => ['label' => 'Gallery 08', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-reception-entrance-night.jpg', 'alt' => 'IXORA Homestay reception entrance lit at night Niduvaloor', 'caption' => 'Reception at night', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.09' => ['label' => 'Gallery 09', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-night-sign-crescent.jpg', 'alt' => 'IXORA Homestay night exterior with welcome sign and crescent moon', 'caption' => 'Night with moon', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.10' => ['label' => 'Gallery 10', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-welcome-sign-garden.jpg', 'alt' => 'IXORA Home Stay Niduvaloor welcome sign beside garden at night', 'caption' => 'Welcome sign garden', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.11' => ['label' => 'Gallery 11', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-brick-garden-feature.jpg', 'alt' => 'Decorative brick garden feature at IXORA Homestay Niduvaloor', 'caption' => 'Garden feature', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.12' => ['label' => 'Gallery 12', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-marigold-garden-swing.jpg', 'alt' => 'Marigold-decorated garden swing at IXORA Homestay Kannur', 'caption' => 'Garden swing night', 'category' => 'photo', 'width' => 1600, 'height' => 1067],
        'gallery.13' => ['label' => 'Gallery 13', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-giraffe-bench-night.jpg', 'alt' => 'Yellow giraffe garden bench under flower arch at IXORA Homestay', 'caption' => 'Giraffe photo bench', 'category' => 'photo', 'width' => 1600, 'height' => 1067],
        'gallery.14' => ['label' => 'Gallery 14', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-double-green.jpg', 'alt' => 'Bright double bedroom with green accents at IXORA Homestay Kannur', 'caption' => 'Bedroom double', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.15' => ['label' => 'Gallery 15', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-wardrobe-view.jpg', 'alt' => 'Spacious bedroom with olive wardrobe at IXORA 2 BHK Homestay', 'caption' => 'Bedroom wardrobe', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.16' => ['label' => 'Gallery 16', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-to-dining.jpg', 'alt' => 'Air-conditioned bedroom opening to dining at IXORA Homestay', 'caption' => 'Bedroom to dining', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.17' => ['label' => 'Gallery 17', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-wood-ceiling.jpg', 'alt' => 'Modern bedroom with wood ceiling at IXORA Homestay Kannur', 'caption' => 'Wood ceiling bedroom', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.18' => ['label' => 'Gallery 18', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-art-wall.jpg', 'alt' => 'Guest bedroom with colourful wall art at IXORA Homestay', 'caption' => 'Bedroom art wall', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.19' => ['label' => 'Gallery 19', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-buddha-art.jpg', 'alt' => 'Clean guest bedroom with artistic decor at IXORA Homestay Kannur', 'caption' => 'Bedroom decor', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.20' => ['label' => 'Gallery 20', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-carrom-night.jpg', 'alt' => 'Spacious bedroom at IXORA Homestay with marble floors, wooden ceiling and carrom board Niduvaloor', 'caption' => 'Bedroom with carrom', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.21' => ['label' => 'Gallery 21', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-buddha-mirror.jpg', 'alt' => 'Modern guest bedroom at IXORA Homestay with dressing mirror and colourful Buddha wall art Kannur', 'caption' => 'Buddha art bedroom', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.22' => ['label' => 'Gallery 22', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-buddha-painting.jpg', 'alt' => 'Cozy IXORA Homestay bedroom with beige bedding and large Buddha painting Niduvaloor', 'caption' => 'Cozy Buddha bedroom', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.23' => ['label' => 'Gallery 23', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-living-room-lounge.jpg', 'alt' => 'Modern living lounge with blue sofas at IXORA Homestay Niduvaloor', 'caption' => 'Living lounge', 'category' => 'living', 'width' => 1600, 'height' => 1067],
        'gallery.24' => ['label' => 'Gallery 24', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-living-room-tv.jpg', 'alt' => 'Indoor living area at IXORA Homestay with patterned chairs and wall-mounted TV Kannur', 'caption' => 'TV lounge seating', 'category' => 'living', 'width' => 1600, 'height' => 1067],
        'gallery.25' => ['label' => 'Gallery 25', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-courtyard-washbasin.jpg', 'alt' => 'Outdoor washbasin with backlit oval mirror at IXORA Homestay Niduvaloor', 'caption' => 'Courtyard washbasin', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.26' => ['label' => 'Gallery 26', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-modern-bathroom.jpg', 'alt' => 'Clean modern bathroom with geometric tiles at IXORA Homestay Kannur', 'caption' => 'Modern tiled bathroom', 'category' => 'living', 'width' => 1600, 'height' => 1067],
        'gallery.27' => ['label' => 'Gallery 27', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-lounge-wooden-ceiling.jpg', 'alt' => 'Guest lounge with white chairs and wooden ceiling at IXORA Homestay Niduvaloor', 'caption' => 'Wood ceiling lounge', 'category' => 'living', 'width' => 1600, 'height' => 1067],
        'gallery.28' => ['label' => 'Gallery 28', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-green-wardrobe.jpg', 'alt' => 'Air-conditioned bedroom with green wardrobe at IXORA Homestay Niduvaloor', 'caption' => 'Green wardrobe room', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.29' => ['label' => 'Gallery 29', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-guest-kitchen.jpg', 'alt' => 'Guest kitchen with mint cabinets, stove and fridge at IXORA Homestay Kannur', 'caption' => 'Green cabinet kitchen', 'category' => 'living', 'width' => 1600, 'height' => 1067],
        'gallery.30' => ['label' => 'Gallery 30', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-dining-room-marble.jpg', 'alt' => 'Indoor dining area with marble-top table and wooden chairs at IXORA Homestay Niduvaloor', 'caption' => 'Marble dining table', 'category' => 'living', 'width' => 1600, 'height' => 1067],
        'gallery.31' => ['label' => 'Gallery 31', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-outdoor-screen-courtyard.jpg', 'alt' => 'Outdoor courtyard with screen stage at IXORA Homestay Kannur', 'caption' => 'Outdoor screen', 'category' => 'events', 'width' => 1600, 'height' => 1067],
        'gallery.32' => ['label' => 'Gallery 32', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-veranda-mural.jpg', 'alt' => 'Sheltered outdoor veranda with traditional mural at IXORA Homestay Kannur', 'caption' => 'Veranda village mural', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.33' => ['label' => 'Gallery 33', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-exterior-aerial.jpg', 'alt' => 'High-angle exterior of IXORA Homestay with red tiled roof amid lush trees Niduvaloor', 'caption' => 'Aerial homestay exterior', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.34' => ['label' => 'Gallery 34', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-garden-walkway-forest.jpg', 'alt' => 'Stone garden walkway beside forest at IXORA Homestay Niduvaloor', 'caption' => 'Garden walkway', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.35' => ['label' => 'Gallery 35', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-courtyard-flower-swing.jpg', 'alt' => 'Yellow garden swing with marigold garlands in the courtyard at IXORA Homestay Kannur', 'caption' => 'Flower garland swing', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.36' => ['label' => 'Gallery 36', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-playground-seesaw.jpg', 'alt' => 'Outdoor play area with yellow swing and seesaw at IXORA Homestay Niduvaloor', 'caption' => 'Swing and seesaw', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.37' => ['label' => 'Gallery 37', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-garden-swing-area.jpg', 'alt' => 'Courtyard garden swing with floral garlands at IXORA Homestay Kannur', 'caption' => 'Garden swing courtyard', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.38' => ['label' => 'Gallery 38', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-terrace-garden-view.jpg', 'alt' => 'Lush plantation view from the terrace at IXORA Homestay Niduvaloor', 'caption' => 'Terrace garden view', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.39' => ['label' => 'Gallery 39', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-garden-walkway-bench.jpg', 'alt' => 'Stone-paved garden walkway with yellow bench at IXORA Homestay Kannur', 'caption' => 'Garden stone walkway', 'category' => 'courtyard', 'width' => 1600, 'height' => 1067],
        'gallery.40' => ['label' => 'Gallery 40', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-plantation-driveway.jpg', 'alt' => 'Red dirt driveway through rubber plantation leading to IXORA Homestay Niduvaloor', 'caption' => 'Plantation entrance path', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.41' => ['label' => 'Gallery 41', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-rubber-plantation-path.jpg', 'alt' => 'Sunny rubber-tree approach path toward IXORA Homestay Kannur', 'caption' => 'Rubber grove approach', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.42' => ['label' => 'Gallery 42', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-main-entrance-gate.jpg', 'alt' => 'Open front gate and green archway at IXORA Homestay Niduvaloor Forest setting', 'caption' => 'Main entrance gate', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.43' => ['label' => 'Gallery 43', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-bedroom-carrom-daylight.jpg', 'alt' => 'Sunlit bedroom with carrom board and green glass door at IXORA Homestay Kannur', 'caption' => 'Sunlit carrom bedroom', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.44' => ['label' => 'Gallery 44', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-cozy-single-bedroom.jpg', 'alt' => 'Cozy single bedroom at IXORA Homestay Niduvaloor Kannur', 'caption' => 'Cozy bedroom', 'category' => 'bedrooms', 'width' => 1600, 'height' => 1067],
        'gallery.45' => ['label' => 'Gallery 45', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-interior-hallway.jpg', 'alt' => 'Bright polished marble hallway at IXORA Homestay Niduvaloor Kannur', 'caption' => 'Marble interior hallway', 'category' => 'homestay', 'width' => 1600, 'height' => 1067],
        'gallery.46' => ['label' => 'Gallery 46', 'group' => 'gallery', 'fallback' => 'assets/images/ixora-homestay-indoor-carrom-room.jpg', 'alt' => 'Indoor recreation room with carrom board at IXORA Homestay Kannur', 'caption' => 'Indoor carrom room', 'category' => 'living', 'width' => 1600, 'height' => 1067],
    ],
];
